# Generated by Django 4.1 on 2022-08-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlertrendyol',
            name='tBrand',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='crawlertrendyol',
            name='tCategory',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='crawlertrendyol',
            name='tMerchantCity',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='crawlertrendyol',
            name='tMerchantName',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='crawlertrendyol',
            name='tMerchantSellerScore',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='crawlertrendyol',
            name='tName',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='crawlertrendyol',
            name='tOtherMerchant',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='crawlertrendyol',
            name='tPriceDiscount',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='crawlertrendyol',
            name='tPriceSell',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
